#mongodb
spring:
#  mongodb连接
  application:
    name: spirng-boot-mongodb
  data:
    mongodb:
      host: 120.79.35.91  #同127.0.0.1
      port: 27017
      database: movierecommendsystem    #指定操作的数据库(中文电影)
#  MySQL连接
  datasource:
    username: root
    password: linrushao
    url: jdbc:mysql://120.79.35.91:3306/bigdata?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
#   Redis连接
  redis:
    host: 120.79.35.91
    port: 6379
    password: linrushao
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms
#  elasticsearch连接
  elasticsearch:
    rest:
      uris: 120.79.35.91:9200
      connection-timeout: 600s
      read-timeout: 600s
